### ISSUE TITLE
Thoughts on FRP?

### ISSUE THREAD

**Issue by walseb** [madjestic/e1339#1]
Hi! I'm just interested in your thoughts on FRP since this new project you have created seems to be going to be structured using MTL and not FRP. I myself has been going back and forth between FRP, MTL and ECS a few times now and my problem with FRP has been mostly performance. In particular performance with dynamic collections in yampa, where it can only process a thousand or so very simple particles that only modify their coordinates every tick before performance slows to a crawl. My hope is that bearriver is faster at this kind of thing but I haven't had the time yet to convert my yampa project.

**Comment by madjestic** [comment]
Yeah, time is an issue...  This project is a kind of a knee-jerk reaction to a recent slag that I hit, as illustrated here:
https://github.com/ivanperez-keera/Yampa/issues/172
https://stackoverflow.com/questions/65609361/n-body-with-yampa-frp-haskell
If you have any experience with this sort of things, please chime in.  I am sure it will be resolved sooner or later, meanwhile I will keep myself busy with other things.

Why MLT?  I've been looking at this project for some time already: https://github.com/anttisalonen/starrover2 
I do like the style, it's readability, simplicity and old-school haskell style.  That's what I mean by "[Lampovy](https://en.wikipedia.org/wiki/Tube_sound)", I am really keen on re-writing my project in that style.  

Considering the FRP performance - I have not yet hit a bottleneck that would be strictly FRP-related (other than that mouse-position sampling problem that you helped me to resolve). 
The biggest challenge that I face with Yampa is still dealing with state, when it's not very trivial - it often becomes a headache like in the example above. I do find myself fighting with abstractions way more than I would have hoped by now, so going a few abstraction layers lower, such as using monad transformers, my expectation is that I can deal with different state easier and fight less with wrapping the state in a specific syntactic construction to satisfy Yampa, although at the cost of loosing some niceties, like automatic time derivatives, integration and portability, that I would have to implement myself...

As far as processing a large amount of objects goes, I am instinctively not even hoping to process such data with a naive FRP update.  I see FRP more as a high-level interface for parts of application talking to each other.  For processing a large number of objects, I would have some sort of sub-routine wrapped up in Yampa/Bearriver/Dunai/etc, that would be using some performance oriented lib, like `massiv`, `accelerate`, `shader compute`, etc., do the necessary number-crunching, package it in some object and send it back to FRP network.  This way I hope to never hit such performance bottlenecks.  Having said that, it would be an interesting benchmark, comparison of approaches, nevertheless, don't you think?

Cheers,
V.

**Comment by madjestic** [comment]
Aaaaaand, the question has been answered. It looks like I really have been missing the basics... Oh my.

**Comment by walseb** [comment]
Sorry for the late reply. Hmm yeah that might solve the performance problems. Now that I have thought about it I guess it would be easiest to just turn those simple particles into a function updating the list of particles instead of using p-switches since I have heard that mass-integrating in particular is slow in FRP because integral doesn't fuse. And it's interesting that you see FRP as a high level language, I never thought of it that way but it's true since I believe a SF is essentially just a function with an implicit time parameter and feedback/rec is like a automated "carry" parameter in a recursive function.

Regarding your now solved problem, yeah rec and state locality in particular is very confusing when you only sort of understand it. I think I have a good grasp of it now but sadly it doesn't work properly in bearriver as of now. By the way, 3D graphics in FRP has become my main focus lately, but I don't have any intention of doing any low-level graphics stuff. So I have begun trying to make binds for ogre-next. Since you have been working on openGL in yampa for a while now, have you checked out ogre and thought about the possibility of using it instead of openGL? I know that there are old failed binds of the library on hackage but I think there is potential there especially given my ignorance of graphics pipelines

Anyways, thanks for the help!

**Comment by madjestic** [comment]
> mass-integrating in particular is slow in FRP because integral doesn't fuse

Does it mean that all integration steps keep existing and never turn into a single final value result?  That would be pretty bad, if that's the case...  But I also remember that there are forgetful switches, so that must be solvable, I would think...

**Comment by walseb** [comment]
No fusion is simply a compiler optimization turning two operations into one so the compiler doesn't have to allocate variables between two mappings for example. This works because the data structure that would be created after running the first `map` and then fed into the second `map` in this function `map . map` would be inaccessible to the user anyways. I believe this isn't done however with SFs such as integral in yampa/dunai. But I could be wrong and even if I'm not, maybe that wasn't my bottleneck

**Comment by madjestic** [comment]
Considering your Ogre question: 
I am not very interested in working on bindings for an existing 3D Engine, such as Ogre, I am afraid.  My focus has been primarily OpenGL/Vulkan and I wanted to create something like a ShaderToy, but using haskell as a backend.  While working on it, I've been slowly adding the feature that I was missing, like importing 3D models, user input, adding multiple projects support, adding geometry data necessary for my OpenGL experiments and generalizing where possible - now it starts looking like a 3D engine of sorts, or ShaderToy on steroids.  
My next step would be adding a GUI and applying what I learnt for other projects, which are not necessarily games.  I am interested in applying ML techniques for price analysis for example.
